### PR TITLE
File resubmit Option 2 - Retain uploaded images when creating new books

### LINKED ISSUE #2760: Add Book Manually Loses The Cover Image Uploaded
**Describe the bug**
When adding a book manually through the UI as a regular user, the cover image doesn't actually get saved and associated with the book.

**To Reproduce**
1. Add book manually
2. Fill out book data, inclusive of adding a cover image
3. Save
4. If linked to existing author/book/edition, the form below clearly shows that no cover image is submitted even if there was a cover image uploaded by the user on the initial form.
5. Generic cover is created and the actual cover has to be uploaded separately once the book is saved.

**Expected behavior**
Data and files entered on the form should save to the form.

**Screenshots**
Form completed with cover image
screenshot-bookwyrm social-2023 03 27-11_45_04

Form retains most data if you need to select existing/new author, but does not retain the file
screenshot-bookwyrm social-2023 03 27-11_45_42

Cover is not uploaded as a result.
screenshot-bookwyrm social-2023 03 27-11_46_14

**Instance**
[On which BookWyrm instance did you encounter this problem.](https://bookwyrm.social/book/935881/s/how-to-be-an-mp) this example is the one I created.

**Additional context**
I've noticed this behavior before, but just re-uploaded the cover.  This was the first time I was able to screenshot the workflow to quantify the issue.

---

**Desktop (please complete the following information):**
    - OS: Manjaro/Budge
    - Browser: FireFox
    - Version: 111.0

### PR DESCRIPTION
**Pull request by hughrun**
django-file-resubmit works ok, but it hasn't been updated for 4 years and seems to be abandoned. It also:

- leaves a file selector visible indicating no file is selected, which is confusing
- is written for Python 2

This PR brings the relevant parts of django-file-resubmit into Bookwyrm directly, under utils, and fixes the issue with the file selector.

Fixes #2760

### CODE REVIEW

**Comment by mouse-reeve** [comment]
Would it potentially make sense to maintain a fork of the library (or a copy of it) in a separate repo under the bookwyrm project rather than including it as a file?

**Comment by hughrun** [comment]
Yes, it would be more sensible! I hadn't thought of doing it as a BookWyrm thing and was reluctant to make a fork I was individually responsible for, since I'm not confident I completely understand all the code.

I can work on that, it would be more like Option one from the perspective of the main project.

**Comment by mouse-reeve** [comment]
Sweet, that all sounds good to me

**Comment by mouse-reeve** [comment]
Oh, let me know if you need me to create anything in the org if there are permissions issues

**Comment by hughrun** [comment]
@mouse-reeve I don't have permission to create a new repo. I actually ran into this problem last week which is why I had to create so many PRs to update the branch for user migration.

A separate issue/question: would this be something we'd want to add to pypi? If so we'll need to work out logistics and workflow for that.

**Comment by mouse-reeve** [comment]
Okay, should I fork it or create a new repo?

**Comment by hughrun** [comment]
> Okay, should I fork it or create a new repo?

I can't see any advantage to a "fork", since the reason we're doing this is that the current repo seems to be abandoned. If I'm understanding correctly, all prior contributors will appear in our new repository. I intend to pull as many of the outstanding PRs as we can do without too much fuss. Probably I'll drop an "Issue" in to the existing repository pointing to ours, which is a bit cheeky but I can't think of any other way to indicate that we've created an active fork.

**Comment by hughrun** [comment]
Sorry didn't actually answer your question. We should do a new repo as this allows us to change the name if we want, and also to change the main branch to `main` instead of `master`.

**Comment by mouse-reeve** [comment]
Perfect -- you should have full control over https://github.com/bookwyrm-social/django-file-resubmit (and you're welcome to change the name)

**Pull request closed without merging**
