### PR TITLE
fixed singularisation/pluralisation

### PR DESCRIPTION
**Pull request by rritik772**
edited two files

### CODE REVIEW

**Comment by rritik772** [comment]
this PR solved the #2625 error. Have a look through it.

**Review by joachimesque — COMMENTED** [review]
Hi, thank you for your contribution!

I’m not 100% up to date with internationalization and Django templates, but I think that using this code won’t allow for the text to be translated in the right way. 

Django templates use a `count` option in its `blocktrans` tag, to specify a plural form:

```
{% blocktrans count count=customers.count %}
  One customer
{% plural %}
  {{ count }} customers
{% endblocktrans %} 
```

Because Django uses `gettext` and `ngettext` for translation, pluralization can only be applied to one variable ([source on stackoverflow](https://stackoverflow.com/a/5244999)). So basically the choice would be either:

A. split the text into multiple strings that are translated apart from each other:

> Current book import is limited to:
> - 50 books
> - every 3 days

B. keep it in one sentence but only pluralize one variable. That solution would work best if we choose the daily limit (IMO an import size limit of 1 will be less used than a reset time of one day).

```
{% blocktrans count days=import_limit_reset %}
  Currently you are allowed to import {{ import_size_limit }} books every {{ days }} day.
{% plural %}
  Currently you are allowed to import {{ import_size_limit }} books every {{ cays }} days.
{% endblocktrans %}
```

**Comment by mouse-reeve** [comment]
@joachimesque is correct, the way this is written unfortunately will not work. I think what makes this complicated is that there are two sources of plurals (book or books, and day or days), but personally I think it would be a reasonable workaround to assume book will be plural because a case where you're only allowed to import 1 book a day seems like a real edge case.

**Comment by rritik772** [comment]
I have edited the file as per Feasibility.

I have an another solution to this problem if you all dont like the solution. We can just replace 
`                <p>{% blocktrans %}Currently you are allowed to import {{ import_size_limit }} books every {{ import_limit_reset }} days.{% endblocktrans %}</p>`
to
`                <p>{% blocktrans %}Currently you are allowed to import {{ import_size_limit }} book/s every {{ import_limit_reset }} day/s.{% endblocktrans %}</p>
`

**Comment by mouse-reeve** [comment]
I like your proposed alternative, but I think it should just assume there are multiple books, so rather than "book/s", just "books"

**Comment by rritik772** [comment]
Ok, That's also reasonable.

**Review by joachimesque — COMMENTED** [review]
Before validating this PR I'd love to have the opinion of translators for various languages for the current solution. Separating the two parts of the sentence might not work universally, though I see no problem with French:

> Actuellement vous pouvez importer un livre
> Actuellement vous pouvez importer {{ import_size_limit }} livres

> par jour.
> tous les {{ import_limit_reset }} jours.

**Comment by mouse-reeve** [comment]
I think it's better to keep whole sentences together, rather than dividing them by internal clauses; it's just hard to predict problems that it could cause in different translations.

**Comment by mouse-reeve** [comment]
I went ahead and did the last little bit of work on this in #2904

**Pull request merged**
