### PR TITLE
Reverts to functional certbot configuration

### PR DESCRIPTION
**Pull request by mouse-reeve**
It turns out the changes to how certbot was configured in https://github.com/bookwyrm-social/bookwyrm/pull/871 don't work. The PR reverts certbot to the previous setup.

@bookwyrm-social/instance-admins - this change is important to make sure your certificate gets renewed. You'll need to comment out line 21 and uncomment line 22 after doing a `git pull` so that the image will be in renew mode instead of install mode. Apologies and let me know if you have any trouble with it!

### CODE REVIEW

**Comment by tofuwabohu** [comment]
Thanks for letting us know! I updated and switched to renewal mode. However, the certificate for wyrms.de will expire on June 13th. It looks to me like certbot renewed, but Firefox still shows the old certificate.
```
# docker-compose logs certbot
Attaching to bookwyrm_certbot_1
certbot_1         | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1         | 
certbot_1         | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1         | Processing /etc/letsencrypt/renewal/wyrms.de.conf
certbot_1         | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1         | Cert is due for renewal, auto-renewing...
certbot_1         | Non-interactive renewal: random delay of 411.150838950377 seconds
certbot_1         | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1         | 
certbot_1         | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1         | Processing /etc/letsencrypt/renewal/wyrms.de.conf
certbot_1         | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1         | Cert is due for renewal, auto-renewing...
certbot_1         | Non-interactive renewal: random delay of 274.0928190589905 seconds
```
Trying to run it manually:
```
# dc exec certbot renew
ERROR: No container found for certbot_1
```
Going through `certbot/logs/letsencrypt.log`, it says te renewal was successful and there's a certificate that expires in September. Will nginx automatically switch to the new one on June 13th or do I have to do something?

**Comment by mouse-reeve** [comment]
Hmmmm I do not know, I have been operating under the assumption that if the certbot logs look good (like yours), then all is well, but I haven't compared the expiration in the browser. My guess is that the switch will happen automatically but I don't know enough about how certificates work to be sure.

**Comment by tofuwabohu** [comment]
Well, we'll see then :)

**Comment by tofuwabohu** [comment]
It's using the new certificate now!

**Comment by mouse-reeve** [comment]
Yay!

**Pull request merged**
