### PR TITLE
Allow BookWyrm Services on Non-Standard Ports

### PR DESCRIPTION
**Pull request by bcj**
My attempt at resolving: https://github.com/bookwyrm-social/bookwyrm/issues/1088

### CODE REVIEW

**Comment by bcj** [comment]
I think once this is done, a related PR would be needed to modify the `.dev` versions of files in the `main` branch. Is that correct?

**Comment by bcj** [comment]
I'm a little stuck on the Redis fixes.
It looks like a bug in `docker-compose.yml` was stopping either redis service from seeing the `redis.conf` file.
Even with that fixed, connections seem to fail when the port isn't `6379`.
Celery does look for Redis on the right port, so it seems like the issue is that Redis ignores the port in the config.
Trying to manually access Redis from my host machine align with this (I'd need to double-check but I think the broker also wasn't accessible on `6379`).

**Comment by bcj** [comment]
Alright, yeah. Just confirmed I can run two instances side-by-side. Non-standard ports work

**Comment by mouse-reeve** [comment]
> I think once this is done, a related PR would be needed to modify the `.dev` versions of files in the `main` branch. Is that correct?

It should all be fine to do in one PR - the prod and main branches are much more in sync now, config-wise

**Comment by bcj** [comment]
dev updated. this should be good to go

**Comment by mouse-reeve** [comment]
Fixes #1088

**Comment by mouse-reeve** [comment]
shoot, I just realized this merged directly into prod - could you make the same PR into main? I realize that sounds like the opposite of what I said before, but the workflow is that I merge into main and then merge main into prod (not obvious! I should have checked!)

**Comment by bcj** [comment]
sure thing

**Pull request merged**
