### PR TITLE
Retain subjects and authors when new book form fails validation

### LINKED ISSUE #2480: Adding new books: "Confirm Book Info" dialog resets Subjects field
When manually adding a new book with Subjects, the form will refresh with the Confirm Book Info panel open at the top. Most data is kept in the form, but the Subjects section does not retain any entered information.

**To Reproduce**
1. Manually add a new book
2. Enter minimally necessary info plus a Subject or two
3. Save
4. When the form refreshes with the Confirm Book Info panel open at the top, scroll down to see that the Subjects block has been reset and is empty.

**Expected behavior**
Subject entries should be retained.

**Instance**
This was tested on bookrastinating.com

---

**Desktop:**
    - OS: MacOS 10.15 Catalina
    - Browser Safari 15.6.1
    - BookWyrm version 0.5.2

### LINKED ISSUE #2571: When validating the form for adding book manually, some fields are emptied if a field is not valid
**Describe the bug**
When adding manually an item (book), if a field is not valid, after hitting enter some fields are emptied (values removed), such as the author, the subject, the cover, etc.

1. Add manually a book.
2. Fill the form with a publication date having only the year.
3. Add an author, subjects and a cover.
4. Save the form.
5. See the emptied fields.

**Expected behavior**
All filled in fields should keep their value after validating the form.

**Instance**
https://bw.diaspodon.fr

**Additional context**

---

**Desktop (please complete the following information):**
    - OS: Archlinux
    - Browser: Firefox
    - Version: 108

### PR DESCRIPTION
**Pull request by hughrun**
Fixes #2480
Fixes #2571

Persists `book.subjects` and `add_author` when form validation fails. The problem here was that `add_author` is not a field in the `Form`, and the template logic is a bit complicated because we use the same form for creating new books and editing existing ones.

This PR does not resolve the problem of cover image uploads being dropped because this is a broader problem and is covered separately in #2760.

### CODE REVIEW

**Review by chdorner — COMMENTED** [review]
Sorry for the delay!

Just tried it locally and it only seems to be working for subjects, but not for authors. Not sure why exactly, could you have another look?

**Comment by hughrun** [comment]
@chdorner hmm I must have missed a step testing. Is this for a brand new book or an edit to an existing one?

**Comment by chdorner** [comment]
> @chdorner hmm I must have missed a step testing. Is this for a brand new book or an edit to an existing one?

Ah that might have been it. I tried editing an existing book, it already had one author stored and I tried to add a second one while making the form validation fail

**Comment by hughrun** [comment]
Ok I didn't look at that workflow but it makes sense that we should fix it too in the same PR - it will be in a different class but I expect it fails for the same reason.

**Comment by chdorner** [comment]
I must be doing something wrong, I now get the following behaviour:

Adding new book:
1. Filling out the form with a published date validation error, and adding 3 subjects and 2 authors
2. No subject or author values are retained, all blank fields

Editing an existing book:
1. Changing the published date to fail validation, and adding 3 subjects and 2 authors
2. All 3 subjects are retained, but the authors aren't

Is that the right way to test this, or am I completely missing something here?

**Comment by hughrun** [comment]
You're testing correctly, though there are two issues to test:

1. Force an error (like a wrong date)
2. Add an author, which creates a checking stage before submitting the final form

Each of these cases is slightly different but we can lose information with both because it's not all stored as `Form` values.

I'm not sure why you are still seeing errors I thought I had fixed but presumably it means I was wrong! I'll take a more exhaustive look at this, sorry about that.

**Comment by hughrun** [comment]
> I must be doing something wrong, I now get the following behaviour

Ok @chdorner I've just re-tested by making a new copy of this PR on my local machine and it works as expected. I'm a bit confused as to why you can't replicate this fix.

**Review by chdorner — APPROVED** [review]
Not sure what I did last time, it does seem to work now as you've described. Sorry for the back and forth!

**Pull request merged**
