### PR TITLE
change how node is installed

### PR DESCRIPTION
**Pull request by jaschaurbach**
Changed how node is installed to the "new" way as the old one is deprecated and will stop to work.

### CODE REVIEW

**Comment by mouse-reeve** [comment]
I'm getting this error when I try to build and run the image:
```
=> ERROR [dev-tools 7/8] RUN mkdir -p /usr/local/node-18.18.0 &&     curl -L https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz | tar Jxf - --strip-components 1 -C /usr/local/node-  11.5s
------                                                                                                                                                                                                    
 > [dev-tools 7/8] RUN mkdir -p /usr/local/node-18.18.0 &&     curl -L https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz | tar Jxf - --strip-components 1 -C /usr/local/node-18.18.0 &&     PATH=/usr/local/node-18.18.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm install --global yarn:                                                                   
0.107   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
0.107                                  Dload  Upload   Total   Spent    Left  Speed
100 22.7M  100 22.7M    0     0  2078k      0  0:00:11  0:00:11 --:--:-- 2036k
11.35 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
------
failed to solve: process "/bin/sh -c mkdir -p /usr/local/node-${NODEVERSION} &&     curl -L https://nodejs.org/dist/v${NODEVERSION}/node-v${NODEVERSION}-linux-x64.tar.xz | tar Jxf - --strip-components 1 -C /usr/local/node-${NODEVERSION} &&     PATH=/usr/local/node-${NODEVERSION}/bin:$PATH npm install --global yarn" did not complete successfully: exit code: 255
```

Do you have any ideas?

**Comment by dato** [comment]
> Changed how node is installed to the "new" way as the old one is deprecated and will stop to work.

Ah yes, the `setup_XX.x` scripts are deprecated, but apt-get can still be used normally ([link](https://github.com/nodesource/distributions#installation-instructions)).

I've tested this approach and left an updated Dockerfile in my repo, in case you want to give it a try? [`main..dato:update-node-installation`](https://github.com/bookwyrm-social/bookwyrm/compare/main...dato:bookwyrm:update-node-installation)

(Extra bit: curl not needed anymore since the sources.file includes the signing key.)

**Comment by jaschaurbach** [comment]
@dato I like your approach even more. Could you create a pull request? Then I would close this one.

**Comment by dato** [comment]
> @dato I like your approach even more.

Thanks for taking a look/

> Could you create a pull request? Then I would close this one.

Done in #3040. Btw, I was unsure whether yarn was needed for something. I can add if it is.

**Comment by jaschaurbach** [comment]
I close this in favor of #3040

**Pull request closed without merging**
