### PR TITLE
fix: missing expand variable

### PR DESCRIPTION
**Pull request by 0x29a**
Discover page is returning error 500 for me.

### CODE REVIEW

**Comment by 0x29a** [comment]
@chdorner, as the author of https://github.com/bookwyrm-social/bookwyrm/pull/2652, would you like to take a look? I'm not sure that `expand` here should be equal to `expand` and not to either `True` or `False`.

**Comment by mouse-reeve** [comment]
`expand` should be set to `False` for this view

**Review by mouse-reeve — CHANGES_REQUESTED** [review]
This will be ready to go with expand set to false :)

**Comment by 0x29a** [comment]
@mouse-reeve, fixed. Thank you for the fast reply. :slightly_smiling_face:

**Comment by mouse-reeve** [comment]
Perfect!

**Review by mouse-reeve — APPROVED** [review]
Perfect!

**Comment by chdorner** [comment]
Oof! Thanks to both of you for fixing this. Great to have it covered by test cases now as well 🎉

**Pull request merged**
