### PR TITLE
Add new user tab listing only reviews and comments

### LINKED ISSUE #2306: Add a Reviews and Comment tab users profile
**Is your feature request related to a problem? Please describe.**
It would be nice to have a user-related feed of reviews and comments made by them.
Right now there's no way to filter out comments/reviews from "wants to read"/"finished reading" making it a bit more difficult to create a discussion/engage with a user.
Adding a "Reviews and Comment" tab in a user profile would help engagement and discussions between users.

**Additional context**
I've added a simple image to show a bit better what I mean with this feature request.
immagine

### PR DESCRIPTION
**Pull request by chdorner**
This is my first PR, please let me know if I've missed anything obvious!

Fixes #2306 by adding a new tab to the user profile which lists the user's activities filtered by Reviews and Comments.

### CODE REVIEW

**Comment by mouse-reeve** [comment]
Yay! Thank you. I should be able to review this tomorrow, but at a glance from my phone it looks like the right thing :)

**Comment by chdorner** [comment]
Not exactly sure why that one test is failing. Shouldn't have anything to do with the code changes, and passes locally as well 🤔

**Comment by mouse-reeve** [comment]
I had a similar problem and I don't know why it's happening! Doesn't seem at all related to your work. I ended up just commenting out that line in the test 😭

**Comment by mouse-reeve** [comment]
Looks good! Thank you

**Pull request merged**
