### PR TITLE
add test for resolving users with aliases

### LINKED ISSUE #3426: `activitypub.resolve_remote_id` throws `IntegrityError` if remote user has unknown alias
**Describe the bug**
Resolving remote users who have unknown users set as an alias may fail.

**To Reproduce**
1. call `activitypub.resolve_remote_id` to retrieve details of remote user A and add them to the local DB
2. remote user A has set remote user B as an alias in their `also_known_as` list
3. remote user B is not known to the local server, and therefore their ID cannot be resolved
4. error: `null value in column "to_user_id" of relation "bookwyrm_user_also_known_as" violates not-null constraint`

**Expected behavior**
`activitypub.resolve_remote_id` should deal with unknown alias users, probably by recursively calling `activitypub.resolve_remote_id` on every alias

**Screenshots**

**Instance**
Development instance

**Additional context**
I stumbled across this when I was doing some work on improving user imports. So caveat on this: I _think_ there is a broader bug, but it's possible this is only relevant for user imports.

Thinking about what is actually happening here, it's possible this is actually even worse because if the user ID does exist in the local DB, would it just set a totally different user as the alias? Need to do some more testing.

---

**Desktop (please complete the following information):**
    - OS: [e.g. iOS]: Docker on Mac
    - Browser [e.g. chrome, safari]: Firefox
    - Version [e.g. 22]: `main` branch

### PR DESCRIPTION
**Pull request by hughrun**
## Description

Adds a test to ensure resolving remote IDs when a user has an `alsoKnownAs` entry is resolved properly.

In #3426 I thought there was a problem, but this test shows that there is not. So I think what I was seeing is when the remote id can't be reached.

- Related Issue #
Closes #3426 

## What type of Pull Request is this?

- [ ] Bug Fix
- [ ] Enhancement
- [x] Plumbing / Internals / Dependencies
- [ ] Refactor

## Does this PR change settings or dependencies, or break something?

- [ ] This PR changes or adds default settings, configuration, or .env values
- [ ] This PR changes or adds dependencies
- [ ] This PR introduces other breaking changes

## Documentation

- [ ] New or amended documentation will be required if this PR is merged
- [ ] I have created a matching pull request in the Documentation repository
- [ ] I intend to create a matching pull request in the Documentation repository after this PR is merged

### Tests

- [ ] My changes do not need new tests
- [x] All tests I have added are passing
- [ ] I have written tests but need help to make them pass
- [ ] I have not written tests and need help to write them

### CODE REVIEW

**Comment by hughrun** [comment]
LOL well I guess all the failing tests kind of prove the point.

Will fix this in a bit.

**Comment by mouse-reeve** [comment]
This is failing in main (it looks like the test is correctly finding that the alias is created incorrectly). I guess what I'm wondering is why it passes here?

**Comment by hughrun** [comment]
Hmm, I suspect this might be because we're running tests concurrently (`pytest -n 3`), and I guess which ones happen to still be running together is slightly different between the two branches?

Within `test_base_activity` we do indeed create 4 users, because we test to see if the default server user is created in one test, but with sequential tests that wouldn't be a problem because each test is supposed to be isolated.

@mouse-reeve using the `--dist=loadfile` flag and value in our pytest runner might help: it makes sure tests within each test file are all assigned to the same worker.

**Comment by hughrun** [comment]
Actually thinking about this more, it's probably because `main` includes the change I made so that all requests are signed, which will force the creation of the server representative user?

I'll see if I can work this out locally and push a fix if possible.

**Comment by mouse-reeve** [comment]
Yes I think that’s it - I was able to recreate the test failure locally running single threaded and I introspected on the user list and iirc the instance user was there so it all checks out

**Pull request merged**
