### PR TITLE
Improving Feed link UI colours 

### PR DESCRIPTION
**Pull request by rkmdCodes**
I have resolved issue #2697.

### CODE REVIEW

**Comment by rkmdCodes** [comment]
hi @hughrun sir thanks for reviewing my PR, currently i am unable to find the dark mode option in original site to test it in production , so  can you please elaborate more about it? I have a little idea that i have to do same changes in theme-dark file too.

**Comment by hughrun** [comment]
@rkmdCodes the dark mode sass file should be in the same directory as the light theme, in `bookwyrm-dark.scss`.

However, a better way to achieve this would be to edit `bookwyrm/components/_tabs.scss` by swapping `$text` and `$link`, which will then ensure it is correct in all themes:

```css
.bw-tabs a {
    ...
    color: $link;
    ...
}

.bw-tabs a:hover {
    ...
    color: $link;
}

.bw-tabs a.is-active {
    ...
    color: $text;
}
```

**Comment by rkmdCodes** [comment]
hi @hughrun sir , I have updated the `_tabs.scss` file and the issue is fixed. Thanks

**Comment by hughrun** [comment]
@rkmdCodes hmm looks like my suggestion doesn't work - did you test this?

**Comment by rkmdCodes** [comment]
hi @hughrun , I have resolved and reimplemented the theme colors for both light and dark theme and I've tested them too. Thanks for the feedback!
image
image

**Comment by rkmdCodes** [comment]
hi @mouse-reeve  can u please take a look at this PR ? Thank You

**Review by hughrun — APPROVED** [review]
Sorry, I led you down the wrong path there! This works, thanks :)

**Comment by rkmdCodes** [comment]
Thank You @hughrun  for approving changes and merging my PR

**Pull request merged**
