### PR TITLE
Allow book subjects to be edited

### PR DESCRIPTION
**Pull request by Tak**
Just adds another comma-separated field below `Languages`

### CODE REVIEW

**Comment by mouse-reeve** [comment]
This is a great change, thank you! Before I merge it, I'm trying to understand the field a bit better to supply some guidance to users about how to use this field. They're sourced from OpenLibrary which doesn't have any info, and doesn't seem to expose them at all in their interface to view or edit books. I thought they might be BISAC subjects, but that doesn't appear to be the case. For example, the "subjects" field in: https://openlibrary.org/books/OL15615497M.json

I think, with a little more info on what kinds of things to suggest, this is a good place for free text fields with an autocomplete trie (which is currently only used when supplying the file link type from the books view).

**Comment by Tak** [comment]
I think they're just freeform tags: see https://github.com/internetarchive/openlibrary/issues/6074

**Comment by mouse-reeve** [comment]
The subjects that are presented in the json view are similar but different than the freeform subjects in the UI -- but it may be that they're just being formatted different or reprocessed? For example, on https://openlibrary.org/books/OL3708706M/Carry_on_Jeeves:

```
"subjects": [
"Wooster, Bertie (Fictitious character) -- Fiction.",
"Jeeves (Fictitious character) -- Fiction.",
"Single men -- Fiction.",
"Valets -- Fiction.",
"England -- Fiction."
],
```
vs

> [Bertie Wooster (Fictitious character)](https://openlibrary.org/subjects/bertie_wooster_(fictitious_character)), [Classic Literature](https://openlibrary.org/subjects/classic_literature), [Valets](https://openlibrary.org/subjects/valets), [Butlers](https://openlibrary.org/subjects/butlers), [Fiction](https://openlibrary.org/subjects/fiction), [Single men](https://openlibrary.org/subjects/single_men), [Humorous stories, English](https://openlibrary.org/subjects/humorous_stories_english), [English Humorous stories](https://openlibrary.org/subjects/english_humorous_stories), [Jeeves (Fictitious character)](https://openlibrary.org/subjects/jeeves_(fictitious_character)), [Jeeves (fictitious character), fiction](https://openlibrary.org/subjects/jeeves_(fictitious_character)_fiction), [Wooster, bertie (fictitious character), fiction](https://openlibrary.org/subjects/wooster_bertie_(fictitious_character)_fiction), [Fiction, humorous](https://openlibrary.org/subjects/fiction_humorous), [England, fiction](https://openlibrary.org/subjects/england_fiction), [Fiction, humorous, general](https://openlibrary.org/subjects/fiction_humorous_general), [British and irish fiction (fictional works by one author)](https://openlibrary.org/subjects/british_and_irish_fiction_(fictional_works_by_one_author))

But I haven't dug into OpenLibrary's github on this, where I'm sure there's an answer. At any rate, it sounds like there isn't some objective standard for this (which makes sense). I think it would be handy to have suggestions to help keep consistency across subject tags, but the trie will need to be generated on the fly, which is a separate coding task outside the scope of this PR

**Comment by mouse-reeve** [comment]
For all my dithering, this is a good change! I'll merge and try to figure out more about how to guide people on metadata in future PRs :)

**Pull request merged**
