### PR TITLE
Improve Open Graph data for books and add it for lists

### LINKED ISSUE #2575: Open Graph tag support for lists
**Is your feature request related to a problem? Please describe.**

When I add a link to [a list](https://bookwyrm.social/list/935/s/book-club-of-two) in e.g. Slack (probably Mastodon/Twitter too?) I get a generic "card" like this:

Screen Shot 2023-01-05 at 12 15 42 PM

**Describe the solution you'd like**

If I'm linking to a list, it would be useful to have list-specific info:
- name of the list
- description
- created/curated by
- maybe number of books?

### PR DESCRIPTION
**Pull request by asmaloney**
- uses book title & description
- adds new data for list
  - title is "Book List: {title} - {site name}"
  - description includes number of books and the owner "{descr} (N books - by {name})"

~~**Note:** I'm not sure how I'm supposed to handle translation of the "N book(s) - by"  text in lists?~~ (thanks Hugh!)

**Examples**

Changes book from:
```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://127.0.0.1/images/previews/covers/2-cc86b02f-a9fc-4dc6-a968-5291af74de6c.jpg">
<meta name="og:image" content="https://127.0.0.1/images/previews/covers/2-cc86b02f-a9fc-4dc6-a968-5291af74de6c.jpg">
<meta name="twitter:image:alt" content="BookWyrm Logo">
<meta name="twitter:title" content="BookWyrm">
<meta name="og:title" content="BookWyrm">
<meta name="twitter:description" content="Social Reading and Reviewing">
<meta name="og:description" content="Social Reading and Reviewing">
```

To:
```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://127.0.0.1/images/previews/covers/2-cc86b02f-a9fc-4dc6-a968-5291af74de6c.jpg">
<meta name="og:image" content="https://127.0.0.1/images/previews/covers/2-cc86b02f-a9fc-4dc6-a968-5291af74de6c.jpg">
<meta name="twitter:image:alt" content="BookWyrm Logo">
<meta name="twitter:title" content="Cooked: A Natural History of Transformation - BookWyrm">
<meta name="og:title" content="Cooked: A Natural History of Transformation - BookWyrm">
<meta name="twitter:description" content="Cooked: A Natural History of Transformation is a 2013 book by Michael Pollan. It details Pollan&#x27;s attempt to learn how to cook several different foods, including barbecue pork, bread, and cheese. He said he wanted to further his culinary education to better feed his family and connect with his teenage son. In Cooked, Pollan asserts that cooking helped modern man evolve and become culturally sophisticated. The book is divided into four sections—Earth, Air, Fire, and Water—and he details how they influence the cooking process.">
<meta name="og:description" content="Cooked: A Natural History of Transformation is a 2013 book by Michael Pollan. It details Pollan&#x27;s attempt to learn how to cook several different foods, including barbecue pork, bread, and cheese. He said he wanted to further his culinary education to better feed his family and connect with his teenage son. In Cooked, Pollan asserts that cooking helped modern man evolve and become culturally sophisticated. The book is divided into four sections—Earth, Air, Fire, and Water—and he details how they influence the cooking process.">
```

Added for lists:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://127.0.0.1/images/">
<meta name="og:image" content="https://127.0.0.1/images/">
<meta name="twitter:image:alt" content="BookWyrm Logo">
<meta name="twitter:title" content="Book List: My Favourite Books - BookWyrm">
<meta name="og:title" content="Book List: My Favourite Books - BookWyrm">
<meta name="twitter:description" content="These are special books. (1 book - by foo-admin@your.domain.here)">
<meta name="og:description" content="These are special books. (1 book - by foo-admin@your.domain.here)">
```

Fixes #2575.

(Again I'm not a Python person so please point out any non-Python-y things!)

### CODE REVIEW

**Comment by asmaloney** [comment]
Apparently `black` can't format f-strings properly...

**Review by hughrun — CHANGES_REQUESTED** [review]
This looks really good! I suggested a couple of changes that should enable this to be translated.

**Comment by asmaloney** [comment]
Thanks @hughrun! That was almost correct & pointed me in the right direction.

I used "_()" to follow the style in the rest of the code.

**Review by hughrun — APPROVED** [review]

**Comment by hughrun** [comment]
Beautiful!

**Pull request merged**
