### PR TITLE
Add a dockerless install method

### PR DESCRIPTION
**Pull request by CactiChameleon9**
I need to do a little bit more testing and the scripts are very welcome to scrutiny... but it does work :tada: 

Hope this is helpful and laid out correctly

Solves #1156

### CODE REVIEW

**Comment by mouse-reeve** [comment]
Thank you so much for this! I wonder if these files should be checked in to the repository, or it would make more sense to have them in the documentation, and ask people to copy/paste the configurations and changes into their install. I think the downsides to that are that the files are a little harder to find, it's less obvious how to update them, and it's more work for the person doing the install to create and edit the files they need.

But the reasons I think it might be better are, since this is a much less common route, it will create less confusion for people doing a traditional install, and (perhaps more importantly), the person doing the install will likely need to change some of the details here based on their own needs. For example if someone didn't want to install in `/opt`. Another reason is that the install script has manual instruction steps, which to me seems like a better fit for a documentation page than a script.

So my proposal, and I'm curious if you agree or have qualms, would be to convert these files into a markdown document in the [documentation repo](https://github.com/bookwyrm-social/documentation/tree/main/content/running_bookwyrm), and re-format it a bit so that it's a set of instructions rather than a script with related files. And fwiw, if you think that sounds good but would prefer not to make the actual markdown files, I'd be happy to do that and make you a co-author on the commits.

**Comment by CactiChameleon9** [comment]
I think I agree with you on the documentation aspect - but I wasn't sure where you wanted this kind a stuff :laughing: (especially with the production and main branch)

I tend to use my code as documentation, if that explains a few of the decisions I made there

Reformatting this into markdown shouldn't be a problem, however I don't think I can do that today. If you are feeling particularly inspired, go ahead - but I should get round to doing that soonish

In the meantime, feel free to close this PR if you want to

**Comment by mouse-reeve** [comment]
Sounds good! I'll leave it to you but feel free to let me know if I can support in any way :)

**Comment by CactiChameleon9** [comment]
Done :)

**Pull request closed without merging**
