### PR TITLE
Audiofic Archive and AO3 IDs

### PR DESCRIPTION
**Pull request by jaschaurbach**
Introduces Audiofic Archive and AO3 IDs to books and authors.

Audiofic ID and AO3 ID will be shown in Ediitons view (people can see that there is an ID and therefore a link to read it)

Audiofic ID and AO3 ID will be whon on author page and will be linked

None of these IDs load any data at the moment, it is just to create the links and to show people the mere existence of these things.

I hacked this together because an existing community of folks reading a certain type of fan fiction and listening to Audiobooks from the Audiofic Archive wants to join my instance. There will be coming more site later...

I introduced a new Format for books:
`("EBook", _("Fanfiction"))`

Please let me know soonish if we could merge this - because if not I will have to think how to proceed with these folks who want to join my BookWyrm instance :)

### CODE REVIEW

**Comment by jaschaurbach** [comment]
Uhm, I have no idea what to fix that the test does not fail

**Comment by jaschaurbach** [comment]
Sorry for the mess -.-

**Comment by mouse-reeve** [comment]
All good! I'll try and take a look at it tomorrow 😌

**Comment by jaschaurbach** [comment]
This is a mess and I close it in favor of smaller pulls requests.

**Comment by mouse-reeve** [comment]
extremely relatable! looking forward to reviewing it when it's in a form your feel good about ❤️

**Pull request closed without merging**
