### PR TITLE
Fixes name of Swedish locale

### PR DESCRIPTION
**Pull request by mouse-reeve**

### CODE REVIEW

**Comment by cincodenada** [comment]
Ha, so fast! Fixes #1902 now 😁 

We should also update the translation files and switch them around, I'm not sure what the process is there though.

**Comment by mouse-reeve** [comment]
ahaha you beat me to it

**Comment by mouse-reeve** [comment]
> We should also update the translation files since it's easy enough to switch them around without having to know the language - I'm not sure what the process is there though.

Yep, that should be a straightforward fix in https://translate.joinbookwyrm.com/

**Comment by cincodenada** [comment]
Great, yeah I realized afterwards that would be a separate thing - how/when do the updated translation files get pushed to Crowdin so that we can update things?

**Comment by mouse-reeve** [comment]
It's manual -- the files are updated using `./bw-dev update_locales`, and once the changes are in `main`, Crowdin detects the updated `en_US` locale file.

**Pull request merged**
