### PR TITLE
Show/Hide password icon

### PR DESCRIPTION
**Pull request by skmanohar**
Addresses #2884 

Adds two new icons, `eye `and `eye-blocked` from icomoon free pack - https://icomoon.io/#preview-free

### CODE REVIEW

**Comment by jaschaurbach** [comment]
It would be great if you would address the failed checks. Thanks!

**Comment by skmanohar** [comment]
Sorting out an error I'm getting during stylelint. Don't run the workflows yet.

**Comment by mouse-reeve** [comment]
Oh sorry I reflexively clicked the workflows before I saw that you just said you weren't ready yet 😅

**Comment by skmanohar** [comment]
Marking this as draft till I figure out what's going on. I'm running into #3032 and #3031. Could very well turn out to be my local issue. Meanwhile, if anyone would like to address #2884 , they could use this PR if it helps.

**Comment by jaschaurbach** [comment]
I updated main to remove one eslint warning which was introduced by me and I just forgot to fix it.

**Pull request merged**
