### PR TITLE
Refactors about page

### LINKED ISSUE #1438: Refactor about page
Right now, the instance "about" page (for example, https://bookwyrm.social/about) shows the instance description and logo, a registration box (or your user profile if you're logged in), and then the code of conduct and privacy policy. It ends up being a wall of text, and while both those documents are important, they're a hard to scan and don't tell you a lot about an instance at a glance. 

I'd like to use this space to give more information about an instance that can be parsed more easily, and let users (and prospective users) drill down into the detailed policies when they are interested in that information.

Some general thoughts:
 - Emphasize the interpersonal relationship between the admins, mods, and users. A fundamental difference between bookwyrm and corporate social media is that bw is designed to be human-scale, and the site should make that clear.
 - Understanding how moderation works - when you report something, who sees it (this can be determined by user permissions, so these users can be displayed automatically) and what kind of actions will they take. 
 - Get a sense of "local flavor" - this may already be addressed by the instance description, but it's good to have space for an instance to communicate what it's about and what the vibe is.
 - Opening the door for users to participate in decision making for the project - I'd like users to feel like they have a say in how the project progresses, and feel heard about what works and doesn't work. And it's a huge help when people feel like they can and should report bugs or frustrations with the software. Right now these conversations are often on GitHub, which is a barrier to people who aren't coders. 
 - Users shouldn't have to understand (or care) about the technical concepts and jargon around federation and decentralization.

Specific thoughts:
 - Show the profile previews of the people who have moderation and administration perms
 - Add a panel about communication with admins (not just for reporting) with some pre-set content and some customizable content
 - Include some general, instance-non-specific information about what bookwyrm is
 - Move the code of conduct and privacy policy to respective pages

### PR DESCRIPTION
**Pull request by mouse-reeve**
The new one has a bunch of info about bookwyrm in general and stats on the specific instance. Also the code of conduct and privacy policy are moved to separate pages.

top of the page:
Screen Shot 2022-01-06 at 9 47 05 AM

and scrolled down:
Screen Shot 2022-01-06 at 9 47 16 AM

Remaining work:
 - [x] migrate superusers to admins
 - [x] handle case when no book superlative is available
 - [x] tests

Fixes #1438 
Depends on https://github.com/bookwyrm-social/join-bookwyrm/pull/37

### CODE REVIEW

**Comment by mouse-reeve** [comment]
I'd love to get feedback from @bookwyrm-social/instance-admins on this

**Comment by Flameborn** [comment]
I like this. Just the fact that the Privacy Policy and the Code of Conduct are separate pages makes it a lot cleaner.

Also, having more stats is always welcome ☺️

**Comment by joachimesque** [comment]
I like that!

**Comment by oragegu** [comment]
It looks great!

**Comment by tofuwabohu** [comment]
Pretty late but I just stumbled upon this. I like it a lot!

**Pull request merged**
