### PR TITLE
Add 'Stopped Reading' shelf

### LINKED ISSUE #1385: Better support for abandoning a book
Currently, if you are reading a book and decide you aren't going to finish it, there is an option in the pulldown menu to "Remove from Currently Reading", which removes the book from your "reading" shelf. It doesn't change anything about the current read-through (if one exists), or mark the book as abandoned. 

It would be useful to hear from people what behavior you'd like to have when you abandon a book -- should it be marked as abandoned? should the button be labelled differently? et cetera

### PR DESCRIPTION
**Pull request by tversteeg**
Fixes #1385.

### CODE REVIEW

**Comment by mouse-reeve** [comment]
Wow thank you! I just approved the automated checks, which will let you know if there are are syntax tweaks or tests failing. If you have any issue resolving them, I'm super happy to help -- running `./bw-dev black` fixes most python issues.

Once I get a chance, I'll check out the code, test it locally, and let you know if anything needs to be tweaked.

Just from the outset, how do you feel about using "stopped reading" rather than "partially read"? To me, "partially read" sounds really similar to "currently reading", whereas "stopped reading" differentiates them.

**Comment by mouse-reeve** [comment]
Sorry about that -- https://github.com/bookwyrm-social/bookwyrm/pull/1941 will fix that but I have to get the dang css linter working first. To run the tests, use `docker-compose run --rm web pytest --no-cov-on-fail`. For black, the version in `requirements.txt` is correct, but likely the version in your dev environment is out of date. Try `docker-compose run --rm web pip install --upgrade black` (or just revert the file that's causing the problem: `git checkout main bookwyrm/templatetags/shelf_tags.py`)

**Comment by mouse-reeve** [comment]
You can fix the tests all failing by creating a merge migration using `./bw-dev makemigrations --merge`. 

There are a few things missing that I saw at a quick test:

1. There's a secret template mode for the reading status models that is used when javascript is unavailable, they just display the modals on their own page. The stopped reading modal needs an analagous modal to the ones that are already there: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/templates/reading_progress/finish.html. If you want to see those in action, you can disable javascript in your browser and click the buttons that open the modals.
2. I'm seeing the shelf change working great, but I have't gotten it to produce a status.
3. The stopped shelf isn't being added for existing users -- you can [add a python function](https://docs.djangoproject.com/en/3.2/ref/migration-operations/#django.db.migrations.operations.RunPython) to the migration that updates existing entries in the database.

Let me know if I can help or you would like me to take on any parts of it. I really appreciate your work on this!

**Comment by tversteeg** [comment]
I've fixed the modal not working without javascript (I love it that you support don't make javascript mandatory, btw).

I'm still working on the status update, which is a bit more work than anticipated, I won't be able to finish that today.

For adding the shelf to existing users using python in the migration, could you help me with that? This is a bit outside my comfort zone, and I'm scared of ruining the database 😄

**Comment by mouse-reeve** [comment]
For sure! I'll do that today. Thank you :)

**Comment by tversteeg** [comment]
That's fine, I feel like this whole PR should be squashed anyway :)
I've got a proper status to show up on my side. I think everything is working fine now but I might miss something..
Thanks for the database script by the way!

**Comment by mouse-reeve** [comment]
I'm ready to merge this -- I'm going to merge it into a local branch so I can fix a couple things I janked up when I added to the migration, and then merge from that branch to main. Thanks for your work and for being patient with the delay on reviewing this!

**Comment by tversteeg** [comment]
No problem, thanks for helping me with this PR and the awesome software!

**Pull request merged**
