### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by mouse-reeve**

### CODE REVIEW

**Comment by kopischke** [comment]
@mouse-reeve shouldn’t at least some of these be merged? I know I’m still missing some of the German translations I suggested, there is a lot of French, Galician and Basque translations  piling up here, and the Chinese ones seem rather exhaustive too …

**Comment by mouse-reeve** [comment]
> @mouse-reeve shouldn’t at least some of these be merged? I know I’m still missing some of the German translations I suggested, there is a lot of French, Galician and Basque translations piling up here, and the Chinese ones seem rather exhaustive too …

Yes, I'm behind on approving translations. I have merged a lot of these in separate PRs, but I need to do another pass-through

**Comment by kopischke** [comment]
> Yes, I'm behind on approving translations. I have merged a lot of these in separate PRs, but I need to do another pass-through

Wouldn’t the simplest solution be to merge this and let Crowdin create new PRs after that? I was under the impression that Crowdin only creates PRs for translations that have gone through their process (i.e. that are either new to hereto untranslated strings, have been approved or ended up upvoted). Approving translations both on Crowdin and in the resulting PRs sounds like an annoyingly redundant amount of work to me, but I could also be missing something.

**Comment by mouse-reeve** [comment]
There are a few reasons, but the most straightforward is that this PR also includes a huge number of currently unused files, and I prefer to only have the ones that are in use.

**Pull request closed without merging**
